### ISSUE TITLE
Android make fails with current instructions

### ISSUE THREAD

**Issue by rishi-rranjan** [dalerank/caesaria-game#4]
With current instructions to build the code for Android, the make command fails with following error: 

In file included from jni/application/core/scopedptr.hpp:21:0,
                 from jni/application/vfs/path.hpp:22,
                 from jni/application/vfs/directory.hpp:21,
                 from jni/application/main.cpp:20:
jni/application/core/requirements.hpp:22:23: fatal error: version.hpp: No such file or directory
 #include "version.hpp"

I changed  "#include "version.hpp"" to " #include "android-version.hpp""  and added path to /android/android-project/jni/src/xcompile in android-project/jni/application/Android.mk  With these changes code compiled.

**Comment by dalerank** [comment]
hi, see .travis.yml instructions for android build. Yes version.hpp is auto create from cmake, but android build havenot cmake environment and need copy fake version.hpp for normal compile.
